spring:
  application:
    name: config-server
  profiles:
    active:
      - native, git
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config
        git:
          uri: https://github.com/iApolloBear/config-repo.git
          searchPaths: licensingservice
server:
  port: 8071
encrypt:
  key: c5b845dde02811a49e06603f832af7324454f541ab0005290344aa776256bba8
management:
  endpoints:
    web:
      exposure:
        include: "*"